version: "2.0"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    hostname: webserver
    ports:
      - "80:8080"

  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pa$$w0rd
    container_name: db
    hostname: mongo_database

  mongo-ui:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pa$$w0rd
      ME_CONFIG_MONGODB_SERVER: db
    container_name: dbui
    hostname: mongo_ui